# Generated by Django 4.2.5 on 2023-09-10 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_recognition.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.ImageField(null=True, upload_to=image_recognition.models.user_directory_path)),
                ('curp', models.ImageField(null=True, upload_to=image_recognition.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
