# Generated by Django 4.2.5 on 2023-09-11 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_recognition', '0004_userinfo_delete_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='documents',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='image_recognition.documents'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
