# Generated by Django 4.2.5 on 2023-10-03 01:26

from django.db import migrations, models
import image_recognition.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognition', '0008_alter_documents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='curp',
            field=models.ImageField(null=True, upload_to=image_recognition.models.curp_directory_path),
        ),
        migrations.AlterField(
            model_name='documents',
            name='identification',
            field=models.ImageField(null=True, upload_to=image_recognition.models.identification_directory_path),
        ),
    ]
